---
- name: Deploying in test server
  hosts: all
  become: yes
  tasks:
  #  - name: update apt
   #   apt: update_cache=yes
    - name: install Docker
      apt:
        name: docker.io
        state: present
    - name: Start Docker container
      docker_container:
        name: testcontainer
        image: 10551jeeva/finance:v1
        state: started
        ports:
          - 8083:8081
    - name: install prometheus
      apt: name=prometheus state=present

    - name: Config prometheus
      ansible.builtin.copy:
        src: prometheus/prometheus_test.yml
        dest: /etc/prometheus/prometheus.yml
    - name: Start prometheus
      shell: sudo systemctl restart prometheus
