---
- name: Deploying in test server
  hosts: testserver
  become: yes
  tasks:
    - name: update apt
      apt: update_cache=yes
    - name: install Docker
      apt:
        name: docker.io
        state: present
    - name: Start Docker container
      docker_container:
        name: addressbook_container
        image: 10551jeeva/finance:v1
        state: started
        ports:
          - 8083:8081
    - name: Config prometheus
      shell: git clone https://github.com/Jeeva-prof/project
      ansible.builtin.copy:
        src: project/prometheus/prometheus_test.yml
        dest: /etc/prometheus/prometheus.yml
        owner: devops
    - name: Config prometheus
      shell: sudo systemctl enable prometheus
